In [1]:
import pandas as pd

In [2]:
reviews = pd.read_csv('reviews_ready_v3.csv')
reviews.info()

C:\Anaconda\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (41,42,44,46,48) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78663 entries, 0 to 78662
Data columns (total 51 columns):
reviewID                   78663 non-null int64
reviewdate                 78663 non-null object
review_id                  78663 non-null object
user_id                    78663 non-null object
review_stars               78663 non-null int64
text                       78663 non-null object
cool                       78663 non-null int64
funny                      78663 non-null int64
useful                     78663 non-null int64
product_sent_cnt           78663 non-null int64
service_sent_cnt           78663 non-null int64
neither_sent_cnt           78663 non-null int64
sentence_cnt               78663 non-null int64
product_word_cnt           78663 non-null int64
service_word_cnt           78663 non-null int64
neither_word_cnt           78663 non-null int64
word_cnt                   78663 non-null int64
reviews_cnt_bf             78663 non-null int64
stars_bf                   78663 non-null object
user_yelping_since         78663 non-null object
user_tenure                78663 non-null int64
user_reviews               78663 non-null int64
user_reviews_bf            78663 non-null int64
user_friends               78663 non-null int64
user_friends_bf_est        78663 non-null int64
user_elites                78663 non-null int64
user_elites_bf             78663 non-null int64
user_useful                78663 non-null int64
user_useful_bf             78663 non-null int64
user_useful2_bf            78663 non-null int64
ID                         78663 non-null int64
business_id                78663 non-null object
categories                 78663 non-null object
name                       78663 non-null object
review_cnt                 78663 non-null int64
review_cnt2                78663 non-null int64
stars                      78663 non-null float64
stars2                     78663 non-null float64
businessID                 78663 non-null int64
Alcohol                    78663 non-null object
Caters                     78663 non-null object
GoodForKids                78663 non-null object
HasTV                      78663 non-null object
NoiseLevel                 78663 non-null object
OutdoorSeating             78663 non-null object
RestaurantsAttire          78663 non-null object
RestaurantsDelivery        78663 non-null object
RestaurantsPriceRange2     78663 non-null int64
RestaurantsReservations    78663 non-null object
RestaurantsTableService    78663 non-null object
WiFi                       78663 non-null object
dtypes: float64(2), int64(29), object(20)
memory usage: 30.6+ MB

In [3]:
reviews.head()

,reviewID,reviewdate,review_id,user_id,review_stars,text,cool,funny,useful,product_sent_cnt,...,GoodForKids,HasTV,NoiseLevel,OutdoorSeating,RestaurantsAttire,RestaurantsDelivery,RestaurantsPriceRange2,RestaurantsReservations,RestaurantsTableService,WiFi
0,1426226,8/24/2008 16:35,0sRfH3GTUXqqxtkKck818Q,DQIt5Uv87fdS54b2oTXBMQ,4,The food is great (5*) but the prices are pret...,0,0,1,3,...,True,True,average,True,casual,True,2,True,TRUE,no
1,1399006,8/24/2008 23:56,#NAME?,TQXtrSpsUyvHMriX8hvNWQ,4,I am crazy for this place and am going as much...,4,6,4,2,...,True,True,average,True,casual,True,2,True,TRUE,no
2,1549809,3/28/2009 5:09,Zr2fR3lldpyR_K0pmN7eOw,SCqaYcRbmXKm6vgyMeIYfg,5,Pio Pio is Awesome!!! I go once a week for lun...,1,0,3,2,...,True,True,average,True,casual,True,2,True,TRUE,no
3,1590566,3/31/2009 17:41,XnpHfKMSSn2u-R50GIm6xw,AIOgdR48J3zgLruPRbtLFw,4,Yummmmy! Just writing this review is making me...,0,0,2,7,...,True,True,average,True,casual,True,2,True,TRUE,no
4,1849132,4/25/2009 23:38,tP4t7SNCCUFoK19KAw3XJw,Uj7HT0E-axR5BbWaN1k04g,5,LOVE LOVE LOVE this place.\nFood is amazingly ...,0,0,2,2,...,True,True,average,True,casual,True,2,True,TRUE,no

In [9]:
# prepare the y and X variables

# 1. let us start with a binary model (if useful>0, d_useful = 1; if useful = 0, d_useful = 1)

reviews['d_useful'] = reviews["useful"].apply(lambda x: 0 if x < 1 else 1)
y = reviews['d_useful']
print(y.value_counts())

# select a list of X variables
X_columns = ['sentence_cnt','product_word_cnt', 'service_word_cnt', 'review_stars']
X = reviews[X_columns]

0    48653
1    30010
Name: d_useful, dtype: int64

In [10]:
# run cross validation
from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 3)

In [11]:
# build a SVM model
from sklearn.svm import SVC, LinearSVC

svc = SVC(C= 1.0, kernel='linear')
svc.fit(X_train, y_train)

y_pred_svc = svc.predict(X_test)

In [ ]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_svc).ravel()
print(confusion_matrix(y_test, y_pred_svc))

# model evaluation 2: Accuracy, sensitivity & specificty
print("Accuracy = %s" %((tp+tn)/(tp+fn+tn+fp)))
print("Sensitivity = %s" %(tp/(tp+fn)))
print("Specificity = %s" %(tn/(tn+fp)))